### ISSUE TITLE
Issue running "npm run iam" 

### ISSUE THREAD

**Issue by rmtuckerphx** [rmtuckerphx/alexa-skill-serverless-starter-template#3]
Heads up, I ran into an issue at the step: 
"npm run iam" Root turned out to be a dependency issue for node-fibers when using the latest version of node - see https://github.com/alexeypetrushin/synchronize/issues/54

**Comment by rmtuckerphx** [comment]
I recommend staying at Node 4.3.2 since that is what Lambda uses: http://docs.aws.amazon.com/lambda/latest/dg/current-supported-versions.html

**Comment by GreenPioneer** [comment]
Hey @rmtuckerphx I have some questions for you on this project if you have time

**Comment by rmtuckerphx** [comment]
Now using Node 6
