### ISSUE TITLE
Path error for listUtility

### ISSUE THREAD

**Issue by jacobweber** [rmtuckerphx/alexa-skill-serverless-starter-template#5]
The file `test/unit/listUtilityTests.js` has the line:
`const ListUtility = require('../../src/listUtility');`
This should be:
`const ListUtility = require('../../src/util/listUtility');`

**Comment by rmtuckerphx** [comment]
Fixed in https://github.com/rmtuckerphx/alexa-skill-serverless-starter-template/commit/c9a6dd073fe6c0e85fa5846860fb32aa5523aef5
